import express from 'express';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import fs from 'fs';

const app = express();
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const PORT = process.env.PORT || 3000;

// Serve static assets generated by Vite in the /dist directory
const distPath = join(__dirname, 'dist');

if (fs.existsSync(distPath)) {
  app.use(express.static(distPath));
}

// Fallback all routes to index.html for SPA (Single Page Application)
app.get('*', (req, res) => {
  const indexPath = join(distPath, 'index.html');
  if (fs.existsSync(indexPath)) {
    res.sendFile(indexPath);
  } else {
    res.status(500).send('Application is building or dist directory is missing. Please run "npm run build" first.');
  }
});

app.listen(PORT, '0.0.0.0', () => {
  console.log(`Fortevia Engenharia web server running on port ${PORT}`);
});
